version: '3'
services:
  express:
    build:
      context: ./
      dockerfile: ./Dockerfile.express
    environment:
      - APP_PORT=3000
      - REDIRECT_URL=http://localhost:3000/static
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/app/app
    